services:
    Heptacom\HeptaConnect\Core\Component\Composer\PackageConfigurationLoader:
        arguments:
            - '%kernel.project_dir%/composer.json'
            - '@cache.system'

    Heptacom\HeptaConnect\Core\Emission\EmitService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Emission\Contract\EmitContextFactoryInterface'
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Core\Emission\Contract\EmitterStackBuilderFactoryInterface'
            - '@Heptacom\HeptaConnect\Core\Emission\Contract\EmissionActorInterface'

    Heptacom\HeptaConnect\Core\Exploration\ExplorationActor:
        arguments:
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Core\Emission\Contract\EmissionActorInterface'
            - '@Heptacom\HeptaConnect\Core\Emission\Contract\EmitContextFactoryInterface'
            - '@Heptacom\HeptaConnect\Portal\Base\Publication\Contract\PublisherInterface'
            - '@Heptacom\HeptaConnect\Core\Emission\Contract\EmitterStackBuilderFactoryInterface'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\Identity\IdentityMapActionInterface'

    Heptacom\HeptaConnect\Core\Exploration\ExploreService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Exploration\Contract\ExploreContextFactoryInterface'
            - '@Heptacom\HeptaConnect\Core\Exploration\ExplorationActor'
            - '@Heptacom\HeptaConnect\Core\Exploration\ExplorerStackBuilderFactory'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Core\Job\Contract\JobDispatcherContract'


    Heptacom\HeptaConnect\Core\Exploration\ExplorerStackBuilderFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Mapping\MappingService:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\MappingExceptionRepository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Component\Composer\PackageConfigurationLoader'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalFactory'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Portal\PortalFactory: ~

    Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\Portal\Contract\PortalStackServiceContainerBuilderInterface'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Core\Portal\PortalRegistry:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalFactory'
            - '@Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalNode\PortalNodeGetActionInterface'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalExtension\PortalExtensionFindActionInterface'

    Heptacom\HeptaConnect\Core\Parallelization\ResourceLocking:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\ResourceLockStorage'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Core\Reception\ReceiverStackBuilderFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Reception\ReceiveService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Reception\Contract\ReceiveContextFactoryInterface'
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Core\Reception\ReceiverStackBuilderFactory'
            - '@Heptacom\HeptaConnect\Core\Reception\ReceptionActor'

    Heptacom\HeptaConnect\Core\Reception\ReceptionActor:
        arguments:
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Portal\Base\Support\Contract\DeepObjectIteratorContract'

    Heptacom\HeptaConnect\Core\Router\Router.lock_store:
        class: Symfony\Component\Lock\Store\FlockStore

    Heptacom\HeptaConnect\Core\Router\Router.lock_factory:
        class: Symfony\Component\Lock\LockFactory
        arguments:
            - '@Heptacom\HeptaConnect\Core\Router\Router.lock_store'

    Heptacom\HeptaConnect\Core\Storage\Normalizer\ScalarDenormalizer:
        tags:
            - { name: heptacom.heptaconnect_denormalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\ScalarNormalizer:
        tags:
            - { name: heptacom.heptaconnect_normalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableDenormalizer:
        tags:
            - { name: heptacom.heptaconnect_denormalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableNormalizer:
        tags:
            - { name: heptacom.heptaconnect_normalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableCompressDenormalizer:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableDenormalizer'
        tags:
            - { name: heptacom.heptaconnect_denormalizer, priority: 100 }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableCompressNormalizer:
        tags:
            - { name: heptacom.heptaconnect_normalizer, priority: 100 }

    Heptacom\HeptaConnect\Core\Support\EntityStatus: ~
