services:
    _instanceof:
        Symfony\Component\Messenger\Handler\MessageSubscriberInterface:
            tags:
                - { name: messenger.message_handler }

    heptacom_heptaconnect.logger:
        class: Psr\Log\LoggerInterface
        factory:
            - '@Shopware\Core\Framework\Log\LoggerFactory'
            - createRotating
        arguments:
            - heptacom_heptaconnect

    Heptacom\HeptaConnect\Core\Component\Composer\PackageConfigurationLoader:
        arguments:
            - '%kernel.project_dir%/composer.json'

    Heptacom\HeptaConnect\Core\Configuration\ConfigurationService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\ConfigurationStorage'

    Heptacom\HeptaConnect\Core\Cronjob\CronjobContextFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'

    Heptacom\HeptaConnect\Core\Cronjob\CronjobService:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage'

    Heptacom\HeptaConnect\Core\Emission\EmitContext:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStorageFactory'

    Heptacom\HeptaConnect\Core\Emission\EmitService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Emission\EmitContext'
            - '@heptacom_heptaconnect.logger'
            - '@messenger.bus.shopware'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'

    Heptacom\HeptaConnect\Core\Exploration\ExploreContextFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStorageFactory'

    Heptacom\HeptaConnect\Core\Exploration\ExploreService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Exploration\ExploreContextFactory'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\Mapping\Publisher'

    Heptacom\HeptaConnect\Core\Mapping\MappingService:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage'

    Heptacom\HeptaConnect\Core\Mapping\Publisher:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage'
            - '@messenger.bus.shopware'

    Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Component\Composer\PackageConfigurationLoader'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalFactory'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Portal\PortalFactory: ~

    Heptacom\HeptaConnect\Core\Portal\PortalRegistry:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalFactory'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage'
            - '@Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader'

    Heptacom\HeptaConnect\Core\Portal\PortalStorageFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Storage\NormalizationRegistry'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage'

    Heptacom\HeptaConnect\Core\Reception\ReceiveContext:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Mapping\MappingService'
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStorageFactory'

    Heptacom\HeptaConnect\Core\Reception\ReceiveService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Mapping\MappingService'
            - '@Heptacom\HeptaConnect\Core\Reception\ReceiveContext'
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'

    Heptacom\HeptaConnect\Core\Router\Router:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Emission\EmitService'
            - '@Heptacom\HeptaConnect\Core\Reception\ReceiveService'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage'
            - '@Heptacom\HeptaConnect\Core\Mapping\MappingService'

    Heptacom\HeptaConnect\Core\Storage\Normalizer\ScalarDenormalizer:
        tags:
            - { name: heptacom.heptaconnect_denormalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\ScalarNormalizer:
        tags:
            - { name: heptacom.heptaconnect_normalizer }

    Heptacom\HeptaConnect\Core\Storage\NormalizationRegistry:
        arguments:
            - !tagged_iterator heptacom.heptaconnect_normalizer
            - !tagged_iterator heptacom.heptaconnect_denormalizer

    Heptacom\HeptaConnect\Core\Webhook\WebhookContextFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'

    Heptacom\HeptaConnect\Core\Webhook\WebhookService:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Webhook\UrlProvider'
