services:
    Heptacom\HeptaConnect\Core\Component\Composer\PackageConfigurationLoader:
        arguments:
            - '%kernel.project_dir%/composer.json'
            - '@cache.system'

    Heptacom\HeptaConnect\Core\Configuration\ConfigurationService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\ConfigurationStorage'
            - '@cache.system'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Core\Cronjob\CronjobService:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\CronjobRepository'

    Heptacom\HeptaConnect\Core\Emission\EmissionActor:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Job\Contract\JobDispatcherContract'
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Repository\RouteRepositoryContract'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Core\Emission\EmitService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Emission\Contract\EmitContextFactoryInterface'
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Core\Emission\Contract\EmitterStackBuilderFactoryInterface'
            - '@Heptacom\HeptaConnect\Core\Emission\EmissionActor'

    Heptacom\HeptaConnect\Core\Exploration\ExplorationActor:
        arguments:
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Core\Mapping\MappingService'
            - '@Heptacom\HeptaConnect\Core\Emission\EmissionActor'
            - '@Heptacom\HeptaConnect\Core\Emission\Contract\EmitContextFactoryInterface'
            - '@Heptacom\HeptaConnect\Portal\Base\Publication\Contract\PublisherInterface'
            - '@Heptacom\HeptaConnect\Core\Emission\Contract\EmitterStackBuilderFactoryInterface'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Core\Exploration\ExploreService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Exploration\Contract\ExploreContextFactoryInterface'
            - '@Heptacom\HeptaConnect\Core\Exploration\ExplorationActor'
            - '@Heptacom\HeptaConnect\Core\Exploration\ExplorerStackBuilderFactory'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Core\Job\Contract\JobDispatcherContract'


    Heptacom\HeptaConnect\Core\Exploration\ExplorerStackBuilderFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Mapping\MappingService:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\MappingRepository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\MappingExceptionRepository'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Repository\MappingNodeRepositoryContract'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Component\Composer\PackageConfigurationLoader'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalFactory'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Portal\PortalFactory: ~

    Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\Portal\Contract\PortalStackServiceContainerBuilderInterface'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Core\Portal\PortalRegistry:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalFactory'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\PortalNodeRepository'
            - '@Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Core\Portal\PortalStorageFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Portal\Base\Serialization\Contract\NormalizationRegistryContract'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\PortalStorage'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Parallelization\ResourceLocking:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\ResourceLockStorage'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Core\Reception\ReceiverStackBuilderFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Reception\ReceiveService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Reception\Contract\ReceiveContextFactoryInterface'
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Core\Reception\ReceiverStackBuilderFactory'
            - '@Heptacom\HeptaConnect\Core\Reception\ReceptionActor'

    Heptacom\HeptaConnect\Core\Reception\ReceptionActor:
        arguments:
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Portal\Base\Support\Contract\DeepObjectIteratorContract'

    Heptacom\HeptaConnect\Core\Router\Router.lock_store:
        class: Symfony\Component\Lock\Store\FlockStore

    Heptacom\HeptaConnect\Core\Router\Router.lock_factory:
        class: Symfony\Component\Lock\LockFactory
        arguments:
            - '@Heptacom\HeptaConnect\Core\Router\Router.lock_store'

    Heptacom\HeptaConnect\Core\Storage\Normalizer\ScalarDenormalizer:
        tags:
            - { name: heptacom.heptaconnect_denormalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\ScalarNormalizer:
        tags:
            - { name: heptacom.heptaconnect_normalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableDenormalizer:
        tags:
            - { name: heptacom.heptaconnect_denormalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableNormalizer:
        tags:
            - { name: heptacom.heptaconnect_normalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableCompressDenormalizer:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableDenormalizer'
        tags:
            - { name: heptacom.heptaconnect_denormalizer, priority: 100 }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableCompressNormalizer:
        tags:
            - { name: heptacom.heptaconnect_normalizer, priority: 100 }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\StreamDenormalizer:
        arguments:
            - '@hepta_connect_bridge_shopware_platform.filesystem.private'
        tags:
            - { name: heptacom.heptaconnect_denormalizer, priority: 200 }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\StreamNormalizer:
        arguments:
            - '@hepta_connect_bridge_shopware_platform.filesystem.private'
        tags:
            - { name: heptacom.heptaconnect_normalizer, priority: 200 }

    Heptacom\HeptaConnect\Core\Support\EntityStatus: ~

    Heptacom\HeptaConnect\Core\Webhook\WebhookService:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\WebhookRepository'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Webhook\UrlProvider'
