services:
    Heptacom\HeptaConnect\Core\Component\Composer\PackageConfigurationLoader:
        arguments:
            - '%kernel.project_dir%/composer.json'
            - '@cache.system'

    Heptacom\HeptaConnect\Core\Exploration\ExplorationActor:
        arguments:
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Core\Emission\Contract\EmissionActorInterface'
            - '@Heptacom\HeptaConnect\Core\Emission\Contract\EmitContextFactoryInterface'
            - '@Heptacom\HeptaConnect\Portal\Base\Publication\Contract\PublisherInterface'
            - '@Heptacom\HeptaConnect\Core\Emission\Contract\EmitterStackBuilderFactoryInterface'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\StorageKeyGeneratorContract'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\Identity\IdentityMapActionInterface'

    Heptacom\HeptaConnect\Core\Exploration\ExploreService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Exploration\Contract\ExploreContextFactoryInterface'
            - '@Heptacom\HeptaConnect\Core\Exploration\ExplorationActor'
            - '@Heptacom\HeptaConnect\Core\Exploration\ExplorerStackBuilderFactory'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Core\Job\Contract\JobDispatcherContract'

    Heptacom\HeptaConnect\Core\Exploration\ExplorerStackBuilderFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Component\Composer\PackageConfigurationLoader'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalFactory'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Portal\PortalFactory: ~

    Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\Portal\Contract\PortalStackServiceContainerBuilderInterface'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\StorageKeyGeneratorContract'

    Heptacom\HeptaConnect\Core\Portal\PortalRegistry:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalFactory'
            - '@Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\StorageKeyGeneratorContract'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalNode\PortalNodeGetActionInterface'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalExtension\PortalExtensionFindActionInterface'

    Heptacom\HeptaConnect\Core\Parallelization\ResourceLocking:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Parallelization\Contract\ResourceLockStorageContract'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\StorageKeyGeneratorContract'

    Heptacom\HeptaConnect\Core\Reception\ReceiverStackBuilderFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Reception\ReceiveService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Reception\Contract\ReceiveContextFactoryInterface'
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\StorageKeyGeneratorContract'
            - '@Heptacom\HeptaConnect\Core\Reception\ReceiverStackBuilderFactory'
            - '@Heptacom\HeptaConnect\Core\Reception\ReceptionActor'

    Heptacom\HeptaConnect\Core\Reception\ReceptionActor:
        arguments:
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Portal\Base\Support\Contract\DeepObjectIteratorContract'

    Heptacom\HeptaConnect\Core\Storage\Normalizer\ScalarDenormalizer:
        tags:
            - { name: heptacom.heptaconnect_denormalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\ScalarNormalizer:
        tags:
            - { name: heptacom.heptaconnect_normalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableDenormalizer:
        tags:
            - { name: heptacom.heptaconnect_denormalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableNormalizer:
        tags:
            - { name: heptacom.heptaconnect_normalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableCompressDenormalizer:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableDenormalizer'
        tags:
            - { name: heptacom.heptaconnect_denormalizer, priority: 100 }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableCompressNormalizer:
        tags:
            - { name: heptacom.heptaconnect_normalizer, priority: 100 }
        arguments:
            - '@Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableNormalizer'

    Heptacom\HeptaConnect\Core\Support\EntityStatus: ~
