services:
    Heptacom\HeptaConnect\Core\Component\Composer\PackageConfigurationLoader:
        arguments:
            - '%kernel.project_dir%/composer.json'
            - '@cache.system'

    Heptacom\HeptaConnect\Core\Configuration\ConfigurationService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\ConfigurationStorage'

    Heptacom\HeptaConnect\Core\Cronjob\CronjobContextFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStorageFactory'
            - '@Heptacom\HeptaConnect\Core\Parallelization\ResourceLocking'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'

    Heptacom\HeptaConnect\Core\Cronjob\CronjobService:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\CronjobRepository'

    Heptacom\HeptaConnect\Core\Emission\EmissionActor:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Job\Contract\JobDispatcherContract'
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\RouteRepository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Core\Emission\EmitContextFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStorageFactory'
            - '@Heptacom\HeptaConnect\Core\Parallelization\ResourceLocking'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'
            - '@Heptacom\HeptaConnect\Core\Mapping\MappingService'

    Heptacom\HeptaConnect\Core\Emission\EmitService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Emission\EmitContextFactory'
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Core\Emission\EmitterStackBuilderFactory'
            - '@Heptacom\HeptaConnect\Core\Emission\EmissionActor'

    Heptacom\HeptaConnect\Core\Emission\EmitterStackBuilderFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Exploration\ExplorationActor:
        arguments:
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Core\Mapping\MappingService'
            - '@Heptacom\HeptaConnect\Core\Emission\EmissionActor'
            - '@Heptacom\HeptaConnect\Core\Emission\EmitContextFactory'
            - '@Heptacom\HeptaConnect\Portal\Base\Publication\Contract\PublisherInterface'
            - '@Heptacom\HeptaConnect\Core\Emission\EmitterStackBuilderFactory'

    Heptacom\HeptaConnect\Core\Exploration\ExploreContextFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStorageFactory'
            - '@Heptacom\HeptaConnect\Core\Parallelization\ResourceLocking'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'

    Heptacom\HeptaConnect\Core\Exploration\ExploreService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Exploration\ExploreContextFactory'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\Exploration\ExplorationActor'
            - '@Heptacom\HeptaConnect\Core\Exploration\ExplorerStackBuilderFactory'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Exploration\ExplorerStackBuilderFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Mapping\MappingService:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\MappingRepository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\MappingExceptionRepository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\MappingNodeRepository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Component\Composer\PackageConfigurationLoader'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalFactory'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Portal\PortalFactory: ~

    Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerBuilder:
        arguments:
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Core\Storage\NormalizationRegistry'

    Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerBuilder'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Core\StatusReporting\StatusReportingContextFactory'

    Heptacom\HeptaConnect\Core\Portal\PortalRegistry:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalFactory'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\PortalNodeRepository'
            - '@Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Core\Portal\PortalStorageFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Storage\NormalizationRegistry'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\PortalStorage'

    Heptacom\HeptaConnect\Core\Parallelization\ResourceLocking:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\ResourceLockStorage'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Core\Reception\ReceiveContext:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Mapping\MappingService'
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStorageFactory'
            - '@Heptacom\HeptaConnect\Core\Parallelization\ResourceLocking'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'
            - '@Heptacom\HeptaConnect\Core\Support\EntityStatus'

    Heptacom\HeptaConnect\Core\Reception\ReceiverStackBuilderFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@heptacom_heptaconnect.logger'

    Heptacom\HeptaConnect\Core\Reception\ReceiveService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Reception\ReceiveContext'
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Core\Reception\ReceiverStackBuilderFactory'
            - '@Heptacom\HeptaConnect\Core\Reception\ReceptionActor'

    Heptacom\HeptaConnect\Core\Reception\ReceptionActor:
        arguments:
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Core\Mapping\MappingService'
            - '@Heptacom\HeptaConnect\Portal\Base\Support\Contract\DeepObjectIteratorContract'

    Heptacom\HeptaConnect\Core\Router\Router.lock_store:
        class: Symfony\Component\Lock\Store\FlockStore

    Heptacom\HeptaConnect\Core\Router\Router.lock_factory:
        class: Symfony\Component\Lock\LockFactory
        arguments:
            - '@Heptacom\HeptaConnect\Core\Router\Router.lock_store'

    Heptacom\HeptaConnect\Core\StatusReporting\StatusReportingContextFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStorageFactory'
            - '@Heptacom\HeptaConnect\Core\Parallelization\ResourceLocking'
        calls:
            - setContainerFactory:
                  - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'

    Heptacom\HeptaConnect\Core\StatusReporting\StatusReportingService:
        arguments:
            - '@Heptacom\HeptaConnect\Core\StatusReporting\StatusReportingContextFactory'
            - '@heptacom_heptaconnect.logger'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Core\Storage\Normalizer\ScalarDenormalizer:
        tags:
            - { name: heptacom.heptaconnect_denormalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\ScalarNormalizer:
        tags:
            - { name: heptacom.heptaconnect_normalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableDenormalizer:
        tags:
            - { name: heptacom.heptaconnect_denormalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\SerializableNormalizer:
        tags:
            - { name: heptacom.heptaconnect_normalizer }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\StreamDenormalizer:
        arguments:
            - '@hepta_connect_bridge_shopware_platform.filesystem.private'
        tags:
            - { name: heptacom.heptaconnect_denormalizer, priority: 10 }

    Heptacom\HeptaConnect\Core\Storage\Normalizer\StreamNormalizer:
        arguments:
            - '@hepta_connect_bridge_shopware_platform.filesystem.private'
        tags:
            - { name: heptacom.heptaconnect_normalizer, priority: 10 }

    Heptacom\HeptaConnect\Core\Storage\NormalizationRegistry:
        arguments:
            - !tagged_iterator heptacom.heptaconnect_normalizer
            - !tagged_iterator heptacom.heptaconnect_denormalizer

    Heptacom\HeptaConnect\Core\Support\EntityStatus: ~

    Heptacom\HeptaConnect\Core\Webhook\WebhookContextFactory:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStorageFactory'
            - '@Heptacom\HeptaConnect\Core\Parallelization\ResourceLocking'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'

    Heptacom\HeptaConnect\Core\Webhook\WebhookService:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\WebhookRepository'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Webhook\UrlProvider'
