services:
    Heptacom\HeptaConnect\Storage\ShopwareDal\ContextFactory: ~

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\EntityType\EntityTypeDefinition:
        tags:
            - { name: shopware.entity.definition, entity: heptaconnect_entity_type }

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\Mapping\MappingDefinition:
        tags:
            - { name: shopware.entity.definition, entity: heptaconnect_mapping }

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\Mapping\MappingErrorMessageDefinition:
        tags:
            - { name: shopware.entity.definition, entity: heptaconnect_mapping_error_message }

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\Mapping\MappingNodeDefinition:
        tags:
            - { name: shopware.entity.definition, entity: heptaconnect_mapping_node }

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\PortalNode\PortalNodeDefinition:
        tags:
            - { name: shopware.entity.definition, entity: heptaconnect_portal_node }

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\PortalNode\PortalNodeStorageDefinition:
        tags:
            - { name: shopware.entity.definition, entity: heptaconnect_portal_node_storage }

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\Job\JobDefinition:
        tags:
            - { name: shopware.entity.definition, entity: heptaconnect_job }

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\Job\JobPayloadDefinition:
        tags:
            - { name: shopware.entity.definition, entity: heptaconnect_job_payload }

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\Job\JobTypeDefinition:
        tags:
            - { name: shopware.entity.definition, entity: heptaconnect_job_type }

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\Route\RouteDefinition:
        tags:
            - { name: shopware.entity.definition, entity: heptaconnect_route }

    Heptacom\HeptaConnect\Storage\ShopwareDal\EntityReflector:
        arguments:
            - '@heptaconnect_mapping.repository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\ContextFactory'

    Heptacom\HeptaConnect\Storage\ShopwareDal\PortalStorage:
        arguments:
            - '@heptaconnect_portal_node_storage.repository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\ContextFactory'

    Heptacom\HeptaConnect\Storage\ShopwareDal\MigrationSource:
        tags:
            - { name: shopware.migration_source }

    Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator: ~

    Heptacom\HeptaConnect\Storage\ShopwareDal\ResourceLockStorage:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\ResourceLockStorage.lock_factory'

    Heptacom\HeptaConnect\Storage\ShopwareDal\ResourceLockStorage.lock_factory:
        class: Symfony\Component\Lock\LockFactory
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Parallelization\FlockStore'
