services:
    _instanceof:
        Shopware\Core\Framework\DataAbstractionLayer\EntityDefinition:
            tags:
                - { name: shopware.entity.definition }

    Heptacom\HeptaConnect\Storage\ShopwareDal\ConfigurationStorage:
        arguments:
            - '@Shopware\Core\System\SystemConfig\SystemConfigService'

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\Cronjob\CronjobDefinition: ~

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\Cronjob\CronjobRunDefinition: ~

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\DatasetEntityType\DatasetEntityTypeDefinition: ~

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\Mapping\MappingDefinition: ~

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\Mapping\MappingErrorMessageDefinition: ~

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\Mapping\MappingNodeDefinition: ~

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\PortalNode\PortalNodeDefinition: ~

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\PortalNode\PortalNodeStorageDefinition: ~

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\Route\RouteDefinition: ~

    Heptacom\HeptaConnect\Storage\ShopwareDal\Content\Webhook\WebhookDefinition: ~

    Heptacom\HeptaConnect\Storage\ShopwareDal\PortalStorage:
        arguments:
            - '@heptaconnect_portal_node_storage.repository'

    Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\CronjobRepository:
        arguments:
            - '@heptaconnect_cronjob.repository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\CronjobRunRepository:
        arguments:
            - '@heptaconnect_cronjob.repository'
            - '@heptaconnect_cronjob_run.repository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\MappingExceptionRepository:
        arguments:
            - '@heptaconnect_error_message.repository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\MappingNodeRepository:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@heptaconnect_mapping_node.repository'
            - '@heptaconnect_dataset_entity_type.repository'

    Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\MappingRepository:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@heptaconnect_mapping.repository'

    Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\PortalNodeRepository:
        arguments:
            - '@heptaconnect_portal_node.repository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\RouteRepository:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@heptaconnect_route.repository'
            - '@heptaconnect_dataset_entity_type.repository'

    Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\WebhookRepository:
        arguments:
            - '@heptaconnect_webhook.repository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator: ~

    Heptacom\HeptaConnect\Storage\ShopwareDal\ResourceLockStorage:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\ResourceLockStorage.lock_factory'

    Heptacom\HeptaConnect\Storage\ShopwareDal\ResourceLockStorage.lock_factory:
        class: Symfony\Component\Lock\LockFactory
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Parallelization\FlockStore'
