services:
    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Database\DatasetEntityTypeDefinition:
        tags:
            - { name: shopware.entity.definition, entity: 'heptaconnect_dataset_entity_type' }
