services:
    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Database\DatasetEntityTypeDefinition:
        tags:
            - { name: shopware.entity.definition, entity: 'heptaconnect_dataset_entity_type' }
    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Database\MappingDefinition:
        tags:
            - { name: shopware.entity.definition, entity: 'heptaconnect_mapping' }
    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Database\MappingNodeDefinition:
        tags:
            - { name: shopware.entity.definition, entity: 'heptaconnect_mapping_node' }
    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Database\PortalNodeDefinition:
        tags:
            - { name: shopware.entity.definition, entity: 'heptaconnect_portal_node' }
    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Database\RouteDefinition:
        tags:
            - { name: shopware.entity.definition, entity: 'heptaconnect_route' }
