imports:
    - { resource: packages/core.yml }
    - { resource: packages/storage-shopware-dal.yml }

services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags:
                - { name: console.command }

        Symfony\Component\Messenger\Handler\MessageSubscriberInterface:
            tags:
                - { name: messenger.message_handler }

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\:
        resource: '../../*'
        exclude:
            - '../../{Resources,Migration,Bundle.php}'
            - '../../Messaging/*/*Message.php'
            - '../../Database/*{Entity,Collection}.php'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalList:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\DataTypeList:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\Explore:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Exploration\ExploreService'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\Router\AddRoute:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\PortalNodeRepository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\Router\ListRoutes:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\PortalNodeRepository'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\Cronjob\EnsureQueue:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\CronjobRunRepository'
            - '@messenger.bus.shopware'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\Cronjob\Queue:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\CronjobRepository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\CronjobRunRepository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@messenger.bus.shopware'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\Configuration\Get:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\Configuration\Reset:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\Configuration\Set:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\AddPortalNode:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\PortalNodeRepository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\ListPortalNodes:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\PortalNodeRepository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\RemovePortalNode:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\PortalNodeRepository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Messaging\Cronjob\CronjobRunHandler:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\CronjobRunRepository'
            - '@Heptacom\HeptaConnect\Core\Cronjob\CronjobContextFactory'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Messaging\Cronjob\CronjobRunMessageHandler:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\CronjobRunRepository'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Messaging\Cronjob\CronjobRunHandler'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage:
        arguments:
            - '@heptaconnect_dataset_entity_type.repository'
            - '@heptaconnect_mapping_node.repository'
            - '@heptaconnect_mapping.repository'
            - '@heptaconnect_route.repository'
            - '@heptaconnect_error_message.repository'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Webhook\WebhookController:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\WebhookRepository'
            - '@Heptacom\HeptaConnect\Core\Webhook\WebhookContextFactory'
        tags:
            - { name: controller.service_arguments }

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Webhook\UrlProvider:
        arguments:
            - '@router.default'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Discovery\Strategy:
        public: true
        calls:
            - [setWebhookService, ['@Heptacom\HeptaConnect\Core\Webhook\WebhookService']]
            - [setCronjobService, ['@Heptacom\HeptaConnect\Core\Cronjob\CronjobService']]
