imports:
    - { resource: packages/core.yml }

services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Shopware\Core\Framework\DataAbstractionLayer\EntityDefinition:
            tags:
                - { name: shopware.entity.definition }

        Symfony\Component\Console\Command\Command:
            tags:
                - { name: console.command }

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\:
        resource: '../../*'
        exclude:
            - '../../{Resources,Migration,Bundle.php}'
            - '../../Database/*{Entity,Collection}.php'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalList:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\DataTypeList:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\Explore:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Exploration\ExploreService'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\Router\AddRoute:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\Router\ListRoutes:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\Cronjob\Queue:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\CronjobStorage'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\Configuration\Get:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\Configuration\Reset:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\Configuration\Set:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Configuration\ConfigurationService'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\AddPortalNode:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\ListPortalNodes:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\RemovePortalNode:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\CronjobStorage:
        arguments:
            - '@heptaconnect_cronjob.repository'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\KeyGenerator'
            - '@heptaconnect_cronjob_run.repository'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\KeyGenerator: ~

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage:
        arguments:
            - '@Shopware\Core\System\SystemConfig\SystemConfigService'
            - '@heptaconnect_dataset_entity_type.repository'
            - '@heptaconnect_mapping_node.repository'
            - '@heptaconnect_mapping.repository'
            - '@heptaconnect_route.repository'
            - '@heptaconnect_error_message.repository'
            - '@heptaconnect_webhook.repository'
            - '@heptaconnect_portal_node.repository'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\KeyGenerator'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\CronjobStorage'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Webhook\WebhookController:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Storage\Storage'
        tags:
            - { name: controller.service_arguments }

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Webhook\UrlProvider:
        arguments:
            - '@router.default'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Discovery\Strategy:
        public: true
        calls:
            - [setWebhookService, ['@Heptacom\HeptaConnect\Core\Component\Webhook\WebhookService']]
            - [setCronjobService, ['@Heptacom\HeptaConnect\Core\Component\Cronjob\CronjobService']]
