imports:
    - { resource: packages/core.xml }
    - { resource: packages/core.yml }
    - { resource: packages/portal.xml }
    - { resource: packages/storage-base.xml }
    - { resource: packages/storage-shopware-dal.xml }
    - { resource: packages/storage-shopware-dal.yml }

services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags:
                - { name: console.command }

        Symfony\Component\Messenger\Handler\MessageSubscriberInterface:
            tags:
                - { name: messenger.message_handler }

    heptacom_heptaconnect.logger:
        class: Psr\Log\LoggerInterface
        factory:
            - '@Shopware\Core\Framework\Log\LoggerFactory'
            - createRotating
        arguments:
            - heptacom_heptaconnect

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalList:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\DataTypeList:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Portal\ComposerPortalLoader'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalStackServiceContainerFactory'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\Explore:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Exploration\ExploreService'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Support\AliasStorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Portal\Base\Publication\Contract\PublisherInterface'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\Configuration\Get:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Configuration\Contract\ConfigurationServiceInterface'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Support\AliasStorageKeyGenerator'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\Configuration\Reset:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Configuration\Contract\ConfigurationServiceInterface'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Support\AliasStorageKeyGenerator'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\Configuration\Set:
        arguments:
            - '@Heptacom\HeptaConnect\Core\Configuration\Contract\ConfigurationServiceInterface'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Support\AliasStorageKeyGenerator'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\AddPortalNode:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Support\AliasStorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalNode\PortalNodeCreateActionInterface'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\ListPortalNodes:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Support\AliasStorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalNode\PortalNodeOverviewActionInterface'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\RemovePortalNode:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Support\AliasStorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalNode\PortalNodeDeleteActionInterface'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\ReportPortalNode:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Support\AliasStorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Core\StatusReporting\Contract\StatusReportingServiceInterface'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\Alias\Get:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalNodeAlias\PortalNodeAliasGetActionInterface'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\Alias\Find:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalNodeAlias\PortalNodeAliasFindActionInterface'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\Alias\Set:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalNodeAlias\PortalNodeAliasSetActionInterface'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Support\AliasStorageKeyGenerator'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\Alias\Reset:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalNodeAlias\PortalNodeAliasSetActionInterface'
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Support\AliasStorageKeyGenerator'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\PortalNode\Alias\Overview:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalNodeAlias\PortalNodeAliasOverviewActionInterface'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Command\TestFlow\Receive:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Support\AliasStorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Core\Reception\ReceiveService'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Core\Mapping\PublisherDecorator:
        decorates: 'Heptacom\HeptaConnect\Portal\Base\Publication\Contract\PublisherInterface'
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Core\Mapping\PublisherDecorator.inner'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
        tags:
            - { name: kernel.event_subscriber }

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Content\KeyAlias\KeyAliasDefinition:
        tags:
            - { name: shopware.entity.definition, entity: heptaconnect_bridge_key_alias }

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Support\AliasStorageKeyGenerator:
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalNodeAlias\PortalNodeAliasFindActionInterface'

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Support\CommandsPrintLogsSubscriber:
        arguments:
            - '@heptacom_heptaconnect.logger'
        tags:
            - { name: kernel.event_subscriber }

    Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Support\MigrationSource:
        tags:
            - { name: shopware.migration_source }
